default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "todolist") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "todolist") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "todolist") %>_production
